- name: Install and run nginx and apache2
  hosts: web
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: present

  #  - name: install apache2
  #    ansible.builtin.package:
  #      name: apache2
  #      state: present

   - name: run nginx
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes


  #  - name: run apache2
  #    ansible.builtin.service:
  #      name: apache2
  #      state: started
  #      enabled: yes     
   
