- name: Deploy web app
  hosts: web
  become: yes
  vars:
    app_name: "My cool App"
    ports: [80, 443]
    config:
      env: "production"
      debug: false
  tasks:
    - name: Print app name
      debug:
        msg: " Deploying {{ app_name }} on ports {{ ports }} in {{ config.env }}"      